### ISSUE TITLE
"Bad" contact information entry causes WP Resume to crash

### ISSUE THREAD

**Issue by kunalashar** [benbalter/feedback#10]
Hi Ben,
I'm using your WP Resume plugin, and encountered an issue of bad data having caused the plugin to become "unrecoverable".
I'm running on WP 4.1 and WP Resume 2.5.7. Everything was working perfectly until I tried something silly.
In the contact information section of WP Resume "Options", I tried adding a new contact row as "Other", but with a URL as the value.
("Other" -> "http://someurl/document.pdf")
Now, the WP Resume plugin doesn't work any more, and throws an error saying "Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 72 bytes) in /home/kunalashar/public_html/gayatrivasan/wp-content/plugins/wp-resume/includes/boilerplate-classes/options.php on line 102"

Removing the offending entry from "Contact Information" doesn't work, and the error continues to remain.

From where in the Resume code or database can I remove the "bad" contact entry?
Thanks in advance.

**Comment by benbalter** [comment]
This is a common WordPress problem, not specific to WP Resume. See http://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP for some additional context and how to bump PHP's memory limit.

**Comment by kunalashar** [comment]
Actually, the problem was related more to the UI's inability to revert/remove the offending entry from WP Resume's system rather than increasing the memory limit.
I figured it out; I went into the database, wp_metadata table, and in the row with the value "wp_wp_resume", I deleted/modified the value containing the additional, overflow data.
