### ISSUE TITLE
Jekyll Exporter - Ability to choose a month range (like the regular xml exporter)

### ISSUE THREAD

**Issue by marteaurouge** [benbalter/feedback#11]
Thanks for your work on the plugin!

Do you think it is possible to add the ability to choose a month range (like the regular xml exporter) ?

Using the plugin is tricky with huge wordpress sites (tried in cli mode, but it didn't work).

**Comment by benbalter** [comment]
A valid ask. Closing in favor of https://github.com/benbalter/wordpress-to-jekyll-exporter/issues/50 over on the jekyll-exporter repository, where others who contribute to the product can get better visibility. Will track progress over there.
