### ISSUE TITLE
WPDocument Revisions

### ISSUE THREAD

**Issue by helms** [benbalter/feedback#12]
Hi.  I'd like to know if WPDocument Revisions is still in active development.  I see it hasn't been updated in a while.  It seems to be the only plugin of it's kind in WP unless you can point me to another that I haven't heard about.

Thanks in advance!

**Comment by natpinit** [comment]
same situation here

**Comment by benbalter** [comment]
I'm still merging pull requests, but have limited time to devote to new feature development, and am [actively looking for contributors or a new maintainer](https://github.com/benbalter/wp-document-revisions/issues/68).
