### ISSUE TITLE
What's the best way to get Github Gov to sponsor Civic Hack events? 

### ISSUE THREAD

**Issue by mateoclarke** [benbalter/feedback#14]
I'm the Brigade Captain for Open Austin. Github is huge in making our org run. 

What is the process to share sponsorship opportunities with Github? Is there a good contact to reach at the company?

For example, we have this event coming up!
https://github.com/open-austin/codeacross-2016/blob/master/sponsorship.md

**Comment by benbalter** [comment]
@mateoclarke Looks awesome! The best place to start is to fill out [this sponsorship request form](https://community.github.com/r/benbalter), which will get the relevant details in front of our sponsorship team. :horse: :us: :meat_on_bone:

**Comment by mateoclarke** [comment]
Thanks!
