### ISSUE TITLE
What are the articles you share the most?

### ISSUE THREAD

**Issue by aaronjorbin** [benbalter/feedback#16]
I saw your [book recommendations](http://ben.balter.com/books-for-geeks/), I was wondering if you had a list of articles/blog posts that you have found equally inspirational and find that you end up sharing often, and what is on that list?

**Comment by benbalter** [comment]
> if you had a list of articles/blog posts that you have found equally inspirational and find that you end up sharing often, and what is on that list?

http://ben.balter.com :trollface: 

In all honesty, if there's a post I find myself linking to a lot, I tried to synthesize it and add contribute to the conversation with my own ideas, but a quick search suggest I find myself often linking out to:

* https://strategyn.com/jobs-to-be-done/
* http://tom.preston-werner.com/2011/11/22/open-source-everything.html
* http://tomayko.com/writings/adopt-an-open-source-process-constraints
* http://newclues.cluetrain.com/ (and http://www.cluetrain.com/)
* https://zachholman.com/posts/how-github-writes-blog-posts/
* https://zachholman.com/posts/github-communication/
* Everything on XKCD
