### ISSUE TITLE
HIPAA... PCI...   what about a standard for Evidence collection in law enforcement?

### ISSUE THREAD

**Issue by vinceyoumans** [benbalter/feedback#17]
Very interesting articles you do.  I am an iPHONE and ANDROID developer that should be using Git more often...  will change that.  I was working on a personal concept for police officers when they collect evidence at a crime scene.  Collecting the evidence is very simple... but I was more focused on protecting identity of witnesses, victims, suspects....  that included synching sinking data to the cloud so that Prosecutors could make desicions... perhaps add some artificial intel to find patterns.  But wissle blowers, and especially witnesses identity should be protected...  As you spent time in Government IT, and seem to have some interesting contacts/resources....  any thoughts on if Law enforcement would be open to the same kind of standards as healthcare or CC?  thanks

**Comment by benbalter** [comment]
>  any thoughts on if Law enforcement would be open to the same kind of standards as healthcare or CC?

@vinceyoumans Unfortunately, you're going to have to ask a licensed attorney in your jurisdiction. I'm afraid that's a bit beyond my area of expertise, and requirements may differ greatly on the local/state/federal law enforcement level. Thanks for reading and thanks for reaching out!
