### ISSUE TITLE
Internal Server Error (500) when running Export to Jekyll Plugin from Wordpress WP-Admin Page (Online)

### ISSUE THREAD

**Issue by jameshamann** [benbalter/feedback#18]
Hi Ben, 

Hope you're well, I wasn't sure whether to post this as an issue on the official repo so I thought I'd let you know here first to see if you're aware of it/working on it. 

As the title suggests, I'm trying to export from WordPress online (I don't have the site files locally) and keep getting a 500 error, not sure if this is due to the recent 4.7 upgrade or anything? 

I look forward to hearing from you. 

Kind Regards, James

*Edit - I've just noticed it's compatible to 4.6.0, apologies.

**Comment by benbalter** [comment]
@jameshamann if you are still having this problem, can you open an issue in https://github.com/benbalter/wp-document-revisions. Thanks! That will get it in front of other users/maintainers and make the conversation more easily discoverable for others who may have a similar request in the future.
