### ISSUE TITLE
WP Document Revisions

### ISSUE THREAD

**Issue by JonathanWilson99** [benbalter/feedback#19]
First off, this is one of my most used plugins for our employee intranet!  Love that we can update a document without worrying about updating URLs etc.!  Thanks!!

I just updated the plugin today, and noticed that after I did, when I went to my Widgets panel to adjust something in my Content Sidebar - all sidebars and menus (and many of the widgets) were gone!  
![image](https://user-images.githubusercontent.com/31417355/29787056-73106fa6-8bfb-11e7-88da-c141bd1058b3.png)
If I clicked on any of the the few on the page, they did not respond, so I clicked 'Manage in Live Preview' only to receive the following:
![image](https://user-images.githubusercontent.com/31417355/29787107-9e63d080-8bfb-11e7-8902-10fd7f38e98b.png)
When I deactivated the WP Document Revisions plugin, I could see all widgets and sidebars again, but once I reactivate the plugin, they're gone again....

Is this something you might be able to look into please?

Thanks so much!
Jonathan

**Comment by benbalter** [comment]
Thanks for this. Think I fixed the issue via https://github.com/benbalter/wp-document-revisions/commit/4478f16ac1478a7080cb647c979d391bf6479a78. The widget code was calling an escaping function that did not exist. If you update to 3.0.1, I believe it should be fixed.

**Comment by JonathanWilson99** [comment]
Perfect Ben, Thank You !!!!!



Thanks,

Jonathan Wilson
Internal Communications Specialist
Big Y Foods, Inc.
2145 Roosevelt Ave.
Springfield, MA 01102
p. 413.504.4048   f. 413.504.6509
