### ISSUE TITLE
Open source workload automation ? Alternative to BMC Control M ?

### ISSUE THREAD

**Issue by ch4huynh** [benbalter/feedback#20]
Thanks for your list that is really convenient.

What would be your recommendation or practice ? I have JobScheduler in mind but it's rather cover only a small scope of what BMC Control M or HP Operations Orchestration can do

**Comment by benbalter** [comment]
I'm sorry @ch4huynh. I don't have any experience with workload automation. A quick Google and GitHub search offered several promising suggestions.
