### ISSUE TITLE
Tips for increasing contributions to a repo

### ISSUE THREAD

**Issue by maya** [benbalter/feedback#22]
Hi @benbalter, we want to make sure the [U.S. Web Design Standards](https://github.com/18F/web-design-standards) continues to be an active, healthy open source project and would love to see more outside contributors picking up and fixing issues. Do you have any recommendations of what we can do? 

- Any changes we should make to our CONTRIBUTING file: https://github.com/18F/web-design-standards/blob/develop/CONTRIBUTING.md?
- We use a `help wanted` label, should we add `good first issue` as well?
- Anything else?

**Comment by benbalter** [comment]
@maya :wave: If you haven't already, I'd recomend checking out https://ben.balter.com/2017/11/10/twelve-tips-for-growing-communities-around-your-open-source-project/ which I wrote a few weeks back to answer this very question.

Slightly older (and I suspect more basic to 18F) is also https://ben.balter.com/2015/03/17/open-source-best-practices-external-engagement/ and https://ben.balter.com/2015/03/08/open-source-best-practices-internal-collaboration/.

> We use a help wanted label, should we add good first issue as well?

Those get special treatment in the UI to increase the project's visibility to potential contributors. Many of the projects I work on use `good first issue` as a way to "guard" issues from regular contributors to reserve them for first time contributors.

> Any changes we should make to our CONTRIBUTING file: https://github.com/18F/web-design-standards/blob/develop/CONTRIBUTING.md?

I'd suggest looking at https://github.com/nayafia/contributing-template, which it looks like you may have already adopted. Here's [my standard contributing file](https://github.com/benbalter/shared-community-files/blob/master/docs/CONTRIBUTING.md), which I created based on best practices I saw in other projects.

Beyond that, my colleague @mikemcquaid uses the concept of [a contributor funnel](https://speakerdeck.com/mikemcquaid/the-open-source-contributor-funnel) to describe the process of converting potential users into users into potential contributors into contributors and ideally, eventually into maintainers and promoters. GitHub doesn't have a turn-key solution (but theoretically, you could build a tool to calculate the number of developers/designers in each stage of the funnel (e.g., downloads, new issues, repeat issues, first time contributors, etc.) and then seek to maximize your conversion rate at each step (or at least identify where the drop off is). More involved than updating documentation, but the strategy could be used to take a more data-driven approach to maximizing contributor conversion.

**Comment by maya** [comment]
Thanks so much @benbalter! Will share this info with our team.
